# Generated by Django 3.2.8 on 2021-11-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_game',
            field=models.CharField(default='dragon quest 8', max_length=500),
            preserve_default=False,
        ),
    ]
