# Generated by Django 3.2.9 on 2021-12-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_favorite_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_game',
        ),
    ]
