# Generated by Django 3.2.9 on 2021-11-12 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
        ('games_owned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesowned',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.game'),
        ),
        migrations.AlterField(
            model_name='gamesowned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
