# Generated by Django 3.2.9 on 2021-11-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_owned', '0002_auto_20211112_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesowned',
            name='owner_rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesowned',
            name='review',
            field=models.CharField(default='a review', max_length=500),
            preserve_default=False,
        ),
    ]
