# Generated by Django 3.2.9 on 2021-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_owned', '0003_auto_20211113_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesowned',
            name='owner_rating',
        ),
        migrations.RemoveField(
            model_name='gamesowned',
            name='review',
        ),
        migrations.AddField(
            model_name='gamesowned',
            name='notes',
            field=models.CharField(default='empty', max_length=150),
            preserve_default=False,
        ),
    ]
