# Generated by Django 3.2.9 on 2021-12-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_owned', '0004_auto_20211215_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesowned',
            name='fixed_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
