# Generated by Django 3.2.9 on 2021-11-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.CharField(default='ps1', max_length=100),
            preserve_default=False,
        ),
    ]
