# Generated by Django 3.2.9 on 2021-12-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
    ]
